# Generated by Django 5.1.3 on 2024-12-15 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_user_bio_post_like_follow_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
    ]
